This dissertation focuses on UAV-based monitoring of cotton maturity during the harvest-aid stage in Xinjiang, with defoliation rate and boll opening rate as the two key agronomic indicators. To address the practical challenges of field investigation, including complex backgrounds, dynamic illumination, low efficiency of manual sampling, and limited deployability of existing methods, the study develops an end-to-end technical pipeline that spans dataset construction, interpretable modeling, lightweight recognition, low-light data generation, all-weather perception, and field validation. The goal is to transform cotton maturity status from an experience-based judgment target into a computable, verifiable, and operationally usable remote-sensing phenotype.

First, a cotton maturity dataset covering multiple acquisition periods, diverse illumination conditions, and complex field backgrounds is established. The study further standardizes image acquisition, manual ground-truth statistics, position parsing, sample organization, and evaluation protocols, providing a consistent data foundation for subsequent experiments. Second, to build an interpretable baseline for maturity recognition, a traditional pipeline of foreground segmentation, handcrafted feature extraction, and machine learning is constructed. Spectral indices, morphological descriptors, and texture statistics are jointly analyzed, enabling the performance gains of later deep models to be interpreted against a traceable reference.

To satisfy edge-deployment constraints, a lightweight dual-indicator recognition model, RTCMNet, is proposed. The model integrates a shared backbone, multi-scale convolutional attention, and dual classification heads, enabling real-time joint recognition of defoliation rate and boll opening rate while maintaining a favorable balance between accuracy, parameter size, and inference speed. To further address low-light and complex illumination scenarios, the dissertation develops a paired low-light data generation pipeline inspired by physical imaging and ISP mechanisms. In the RGB domain, the pipeline jointly simulates exposure attenuation, white-balance drift, Poisson-Gaussian noise, mild blur, and vignetting, and uses real nighttime UAV images for statistical calibration, thus providing controllable supervision for subsequent enhancement and robust recognition.

On top of this data foundation, a lightweight enhancement front-end, $L^3$-AgriUAVNet, is designed and coupled with the dual-indicator recognition model to form an all-weather recognition pipeline. The results show that the enhancement module improves luminance distribution, structural restoration, and color stability, and strengthens the robustness of downstream recognition under low-light, shadowed, and backlit conditions. Finally, the complete pipeline is embedded into real field operations. Through multi-temporal UAV acquisition, online recognition, geographic mapping, and manual verification, the spatial distribution and temporal evolution of cotton maturity are systematically analyzed. The results demonstrate that the proposed method can stably identify delayed-maturity zones, local anomalous areas, and maturity progression regions, suggesting its applicability in real agricultural scenarios.

This work establishes a systematic research path from data and algorithms to field-level validation for cotton maturity monitoring. The study provides a useful reference for intelligent monitoring of cotton maturity, harvest-aid decision support, and robust visual perception in agricultural environments with dynamic illumination.
