Harvest-aid application is an important operation in mechanized cotton production in Xinjiang. The progression of defoliation and boll opening directly affects harvest timing and picking quality. Timely assessment of both indicators and their spatial distribution is therefore essential for evaluating treatment effects and identifying areas where maturation is delayed. However, manual field surveys are labor-intensive and time-consuming, and a limited number of sampling points cannot adequately represent spatial variation across large cotton fields. Unmanned aerial vehicle (UAV) RGB imagery offers a means of rapidly acquiring canopy information, but joint recognition of defoliation rate and boll opening rate remains challenging because of canopy–background interference, differences in the progression of the two traits, and reduced visibility of discriminative features under low illumination. Limited computing resources on field devices further constrain the use of complex models. This dissertation investigates visible-image phenotypic features, lightweight joint recognition, and low-light image adaptation for cotton at maturity. By linking image predictions with geographic locations and observations over time, it develops a monitoring workflow that connects canopy imagery to field-scale representations of maturation. The main research contributions and findings are as follows:

(1) A multi-temporal cotton image dataset with labels for both defoliation rate and boll opening rate was constructed, and the capacity of visible-image features to represent the two maturity indicators was examined. UAV imagery was linked to manual field surveys to assign grade labels for both indicators to each image sample. To address background interference and poor classification performance when using high-dimensional pixel inputs directly, structured features based on color and visible-light index statistics were constructed and compared with pixel-vector representations. The highest macro-F1 scores obtained with structured features were 0.867 for defoliation rate and 0.830 for boll opening rate, both exceeding the pixel-vector baselines. Feature analysis showed that changes in canopy greenness were closely associated with both maturity grades, while color statistics remained sensitive to illumination degradation. These findings informed the subsequent development of joint recognition and low-light adaptation methods.

(2) A low-light data synthesis and lightweight enhancement method was proposed for agricultural UAV imagery. To address the difficulty of obtaining precisely paired low-light and normally exposed images and the shortage of agricultural training data, a controllable degradation model inspired by the imaging process was constructed. Its parameters were calibrated using real low-light images to generate paired training samples. A lightweight enhancement network, $L^3$-AgriUAVNet, was then designed to combine local detail extraction with global color and brightness adjustment, balancing canopy structure visibility and computational cost. With 0.139 M parameters, the model achieved a structural similarity index of 0.893 on the synthetic paired test set and improved the visibility of vegetation in dark regions and inter-row structures in real low-light images. Downstream maize-seedling detection further showed that enhancement benefits varied with detector configuration, indicating that visual improvement must be evaluated in relation to the specific recognition task.

(3) A lightweight joint recognition network, RTCMNet, was proposed to balance recognition performance and computation on edge devices. Defoliation and boll opening share canopy-level visual cues but differ in their local discriminative features. RTCMNet therefore uses a shared backbone and task-specific classification heads, together with multi-scale convolutional attention to capture information about residual leaves, exposed cotton lint, and canopy density at different spatial scales. In five-fold cross-validation within the target operating domain, mean accuracy and macro-F1 across the two tasks were both $0.93 plus.minus 0.02$, approaching the performance of larger comparison models. The network contains 0.37 M parameters and requires 32 ms per image for inference on a UAV remote controller. By combining joint recognition with lightweight deployment, the method provides a model basis for rapid assessment of cotton maturity in the field.

(4) A workflow for mapping the spatial and temporal distributions of both predicted indicators was established and evaluated in production cotton fields under normal and low illumination. Predictions were mapped to UAV sampling locations and compared across stages after harvest-aid application. Both predicted indicator grades increased overall as maturation progressed, while local differences in their progression and delays near field boundaries remained visible. Some anomalous locations corresponded to field observations. For sunset imagery, cascading the enhancement network with RTCMNet enabled low-light image processing and spatial mapping, with prediction changes varying by maturation stage and task. The field results support the use of dual-indicator maps to locate areas of interest and guide field verification; quantifying any improvement in cotton recognition accuracy from low-light enhancement still requires concurrent ground-truth measurements.

This dissertation connects visible-image feature analysis, lightweight joint recognition, low-light input adaptation, and spatial mapping to support monitoring of cotton responses to harvest-aid application. The resulting workflow extends image-sample recognition to the analysis of within-field variation. The methods and data provide a basis for repeated observation of cotton at maturity and verification of local anomalies, supporting further use of UAV remote sensing in field management for mechanized cotton production.
