#import "../template.typ": booktab

#booktab(
  columns: (1.5fr, 2.7fr, 2.3fr),
  outlined: false,
  align: (left, left, left),
  [符号或缩写],
  [英文全称],
  [中文],
  [$"DE"_t$],
  [Defoliation Rate on Day $t$],
  [第 $t$ 天脱叶率],
  [$"BA"_t$],
  [Boll Opening Rate on Day $t$],
  [第 $t$ 天吐絮率],
  [$L_0$],
  [Initial Leaf Count],
  [施药初始叶片数],
  [$L_t$],
  [Leaf Count on Day $t$],
  [第 $t$ 天叶片数],
  [$B_0$],
  [Initial Total Boll Count],
  [施药初始棉铃总数],
  [$B_t$],
  [Open Boll Count on Day $t$],
  [第 $t$ 天开裂棉铃数],
  [UAV],
  [Unmanned Aerial Vehicle],
  [无人机],
  [RGB],
  [Red, Green, Blue],
  [红绿蓝三通道图像],
  [RGB-D],
  [Red, Green, Blue and Depth],
  [彩色-深度多模态数据],
  [CNN],
  [Convolutional Neural Network],
  [卷积神经网络],
  [RTCMNet],
  [Real-Time Cotton Monitoring Network],
  [棉花脱叶率与吐絮率实时监测网络],
  [MSCA],
  [Multi-Scale Convolutional Attention],
  [多尺度卷积注意力],
  [ESA],
  [Enhanced Spatial Attention],
  [增强空间注意力],
  [GMod],
  [Global Modulation],
  [全局调制模块],
  [HVI],
  [Horizontal/Vertical-Intensity],
  [水平/垂直-强度颜色表征],
  [RFDN-S],
  [Residual Feature Distillation Network--Shallow Variant],
  [浅层残差特征蒸馏块],
  [GSD],
  [Ground Sampling Distance],
  [地面分辨率],
  [RTK],
  [Real-Time Kinematic],
  [实时动态定位],
  [PPK],
  [Post-Processed Kinematic],
  [后处理动态定位],
  [GCP],
  [Ground Control Point],
  [地面控制点],
  [ROI],
  [Region of Interest],
  [感兴趣区域],
  [PCA],
  [Principal Component Analysis],
  [主成分分析],
  [LR],
  [Logistic Regression],
  [逻辑回归],
  [SVM],
  [Support Vector Machine],
  [支持向量机],
  [RF],
  [Random Forest],
  [随机森林],
  [SPAD],
  [Soil and Plant Analyzer Development],
  [叶绿素相对含量指标],
  [ExG],
  [Excess Green Index],
  [超绿指数],
  [VARI],
  [Visible Atmospherically Resistant Index],
  [可见光抗大气植被指数],
  [NGRDI],
  [Normalized Green-Red Difference Index],
  [归一化绿红差异指数],
  [ISP],
  [Image Signal Processing],
  [图像信号处理],
  [RAW],
  [Raw Sensor Data],
  [原始传感器数据],
  [LiDAR],
  [Light Detection and Ranging],
  [激光雷达],
  [PSNR],
  [Peak Signal-to-Noise Ratio],
  [峰值信噪比],
  [SSIM],
  [Structural Similarity Index Measure],
  [结构相似性指标],
  [LPIPS],
  [Learned Perceptual Image Patch Similarity],
  [学习感知图像块相似度],
  [MAE],
  [Mean Absolute Error],
  [平均绝对误差],
  [Macro-F1],
  [Macro-Averaged F1 Score],
  [宏平均 F1 值],
  [mAP],
  [mean Average Precision],
  [平均精度均值],
  [IoU],
  [Intersection over Union],
  [交并比],
  [GMACs],
  [Giga Multiply-Accumulate Operations],
  [十亿次乘加运算],
  [ONNX],
  [Open Neural Network Exchange],
  [开放神经网络交换格式],
  [YOLOv8n],
  [YOLO Version 8 Nano],
  [YOLOv8 纳米型检测模型],
  [YOLOv8s],
  [YOLO Version 8 Small],
  [YOLOv8 小型检测模型],
  [LOW],
  [Original Low-Light Input],
  [原始低光输入],
  [EN],
  [Enhanced Input],
  [增强输入],
)
