#import "../template.typ": booktab

#booktab(
  columns: (1.5fr, 2.7fr, 2.3fr),
  outlined: false,
  align: (left, left, left),
  [符号或缩写],
  [英文名称或释义],
  [中文含义],
  [$"DE"_t$],
  [Defoliation Rate on Day $t$],
  [第 $t$ 天脱叶率],
  [$"BA"_t$],
  [Boll Opening Rate on Day $t$],
  [第 $t$ 天吐絮率],
  [$L_0$],
  [Initial Leaf Count],
  [施药初始叶片数],
  [$L_t$],
  [Leaf Count on Day $t$],
  [第 $t$ 天残留叶片数],
  [$B_0$],
  [Initial Total Boll Count],
  [施药初始棉铃总数],
  [$B_t$],
  [Open Boll Count on Day $t$],
  [第 $t$ 天开放棉铃数],
  [$D_("GR",3)$],
  [Green–Red Difference Normalized by RGB Sum],
  [以三通道之和归一化的绿红差异量，区别于标准 VARI],
  [$mu(Z)$、$sigma(Z)$],
  [Mean and Standard Deviation],
  [通道或指数图 $Z$ 的像素均值与标准差],
  [$Q_10$、$Q_50$、$Q_90$],
  [10th, 50th and 90th Percentiles],
  [像素值的第 10、50、90 百分位数],
  [$alpha$],
  [Exposure Attenuation Factor],
  [低光合成中的曝光衰减系数],
  [$sigma_r$、$sigma_b$],
  [Noise and Blur Standard Deviations],
  [读出噪声与高斯模糊的标准差参数],
  [$D_("RGB")$],
  [Relative RGB Channel Imbalance],
  [RGB 通道均值的相对不均衡度],
  [UAV],
  [Unmanned Aerial Vehicle],
  [无人机],
  [RGB],
  [Red, Green, Blue],
  [红绿蓝三通道图像],
  [RGB-D],
  [Red, Green, Blue and Depth],
  [彩色-深度多模态数据],
  [CNN],
  [Convolutional Neural Network],
  [卷积神经网络],
  [GAN],
  [Generative Adversarial Network],
  [生成对抗网络],
  [ViT],
  [Vision Transformer],
  [视觉 Transformer；ViT-S 为其小型配置],
  [LLFormer],
  [Low-Light Transformer],
  [低光图像增强 Transformer 模型],
  [$L^3$-AgriUAVNet],
  [—],
  [本文提出的农业无人机影像轻量级低光增强网络],
  [RTCMNet],
  [Real-Time Cotton Monitoring Network],
  [棉花脱叶率与吐絮率实时监测网络],
  [BN],
  [Batch Normalization],
  [批归一化],
  [MLP],
  [Multilayer Perceptron],
  [多层感知机],
  [GAP],
  [Global Average Pooling],
  [全局平均池化],
  [MSCA],
  [Multi-Scale Convolutional Attention],
  [多尺度卷积注意力],
  [ESA],
  [Enhanced Spatial Attention],
  [增强空间注意力],
  [GMod],
  [Global Modulation],
  [全局调制模块],
  [HVI],
  [Horizontal/Vertical-Intensity],
  [水平/垂直-强度颜色表征],
  [RFDN / RFDB],
  [Residual Feature Distillation Network / Block],
  [残差特征蒸馏网络／块],
  [RFDN-S],
  [Residual Feature Distillation Network--Shallow Variant],
  [浅层残差特征蒸馏块],
  [GSD],
  [Ground Sampling Distance],
  [地面分辨率],
  [RTK],
  [Real-Time Kinematic],
  [实时动态定位],
  [PPK],
  [Post-Processed Kinematic],
  [后处理动态定位],
  [GCP],
  [Ground Control Point],
  [地面控制点],
  [ROI],
  [Region of Interest],
  [感兴趣区域],
  [PCA],
  [Principal Component Analysis],
  [主成分分析],
  [LR],
  [Logistic Regression],
  [逻辑回归],
  [SVM],
  [Support Vector Machine],
  [支持向量机],
  [RBF],
  [Radial Basis Function],
  [径向基函数；本文用于 SVM 核函数],
  [RF],
  [Random Forest],
  [随机森林],
  [SPAD],
  [Soil and Plant Analyzer Development],
  [叶绿素相对含量指标],
  [ExG],
  [Excess Green Index],
  [超绿指数],
  [VARI],
  [Visible Atmospherically Resistant Index],
  [可见光抗大气植被指数],
  [NGRDI],
  [Normalized Green-Red Difference Index],
  [归一化绿红差异指数],
  [ISP],
  [Image Signal Processing],
  [图像信号处理],
  [PSF],
  [Point Spread Function],
  [点扩散函数],
  [CDF],
  [Cumulative Distribution Function],
  [累积分布函数],
  [RAW],
  [Raw Sensor Data],
  [成像链路中的原始传感器数据],
  [LiDAR],
  [Light Detection and Ranging],
  [激光雷达],
  [PSNR],
  [Peak Signal-to-Noise Ratio],
  [峰值信噪比],
  [SSIM],
  [Structural Similarity Index Measure],
  [结构相似性指标],
  [LPIPS],
  [Learned Perceptual Image Patch Similarity],
  [学习感知图像块相似度],
  [NIQE],
  [Natural Image Quality Evaluator],
  [自然图像质量评价指标],
  [BRISQUE],
  [Blind/Referenceless Image Spatial Quality Evaluator],
  [无参考图像空间质量评价指标],
  [MAE],
  [Mean Absolute Error],
  [平均绝对误差],
  [Macro-F1],
  [Macro-Averaged F1 Score],
  [宏平均 F1 值],
  [mAP],
  [mean Average Precision],
  [平均精度均值],
  [IoU],
  [Intersection over Union],
  [交并比],
  [MACs],
  [Multiply–Accumulate Operations],
  [乘加运算次数],
  [GMACs],
  [Giga Multiply-Accumulate Operations],
  [十亿次乘加运算],
  [CPU],
  [Central Processing Unit],
  [中央处理器],
  [GPU],
  [Graphics Processing Unit],
  [图形处理器],
  [WASM],
  [WebAssembly],
  [浏览器 CPU 推理使用的 WebAssembly 执行技术],
  [FPS],
  [Frames per Second],
  [每秒处理帧数；本文测速按每秒推理次数报告],
  [P50、P90、P95],
  [50th, 90th and 95th Percentiles of Latency],
  [推理耗时的第 50、90、95 百分位数],
  [ONNX],
  [Open Neural Network Exchange],
  [开放神经网络交换格式],
  [ORT],
  [ONNX Runtime],
  [ONNX 模型推理运行时],
  [YOLOv8n],
  [YOLO Version 8 Nano],
  [YOLOv8 纳米型检测模型],
  [YOLOv8s],
  [YOLO Version 8 Small],
  [YOLOv8 小型检测模型],
  [Raw / RAW（输入标签）],
  [Original Input without Enhancement],
  [第 3 章为正常光照基线；第 4 章 Raw 为未经增强的低光输入],
  [LOW],
  [Original Low-Light Input],
  [原始低光输入],
  [EN],
  [Enhanced Input],
  [增强输入],
)
